#!/usr/bin/env bash

#INFO: zlp - launcher + wrapper for zsh completion LSP
# Usage:
# 0 argv:   start server.js
# else:     parse the input-string, zsh-magic it, and return completions

# Adjust with `export`
LZP_PROJECT_DIR="${LZP_PROJECT_DIR:-${HOME}/projects/lzp}"
LZP_CAPTURE_SCRIPT="${LZP_COMPLETION_SCRIPT_PATH:-${LZP_PROJECT_DIR}/capture.zsh}"
LZP_NODE_SERVER="${LZP_NODE_SERVER:-${LZP_PROJECT_DIR}/server.js}"

if [[ $# -eq 0 ]]; then
    exec node "${LZP_NODE_SERVER}"
fi

if [[ ! -e "${LZP_CAPTURE_SCRIPT}" ]]; then
    printf '\e[31mERROR: %s does not exist\e[0m\n' "${LZP_CAPTURE_SCRIPT}"
    exit 1
elif [[ ! -x "${LZP_CAPTURE_SCRIPT}" ]]; then
    printf '\e[31mERROR: %s exists, but is not executable\e[0m\n' "${LZP_CAPTURE_SCRIPT} "
    exit 2
fi

exec "${LZP_CAPTURE_SCRIPT}" "$1"
